---
# yamllint disable rule:truthy
version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: main
    labels:
      - "changes/patch"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: main
    labels:
      - "changes/patch"
    groups:
      all:
        patterns:
          - "*"