---
# yamllint disable rule:truthy
version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token # username doesn't matter
    password: ${{ secrets.DEPENDABOT_TOKEN }} # dependabot secret

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: main
    labels:
      - "changes/patch"
    groups:
      all:
        patterns:
          - "*"
    registries:
      - github

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: main
    labels:
      - "changes/patch"
    groups:
      all:
        patterns:
          - "*"
    registries:
      - github
