name: Handle Dependabot Trigger

on:
  repository_dispatch:
    types:
      - force-dependabot-update

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run Dependabot update
      - name: Run Dependabot Update
        uses: dependabot/fetch-metadata@v2

