name: Handle Submodule Trigger

on:
  repository_dispatch:
    types:
      - force-submodule-update

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # # Run Dependabot update
      # - name: Run Dependabot Update
      #   uses: dependabot/fetch-metadata@v2

      - name: Set branch name
        id: set-branch-name
        run: |
          SUBMODULE_PATH="infrahub-sdk-python"
          RELEASE_VERSION="${{ github.event.client_payload.version }}"
          BRANCH_NAME="${SUBMODULE_PATH}-${RELEASE_VERSION}"
          echo "SUBMODULE_PATH=$SUBMODULE_PATH" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Use the version from client payload to update submodule
        run: |
          echo "Updating submodule to version: ${{ env.RELEASE_VERSION }}"
          echo "Branch name: ${{ env.BRANCH_NAME }}"

          # Navigate to the submodule and update it to the specified version
          cd infrahub-sdk-python
          git fetch --tags
          git checkout ${{ env.RELEASE_VERSION }}
          cd -

      - name: Commit and push changes with github-actions-x/commit
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.OTTO_TOKEN }}
          push-branch: ${{ env.BRANCH_NAME }}
          commit-message: "chore: update submodule ${{ env.SUBMODULE_PATH }} to version ${{ env.RELEASE_VERSION }}"
          files: infrahub-sdk-python/
          name: opsmill-bot
          email: github-bot@opsmill.com
          rebase: false

      - name: Create a pull request
        run: |
          echo ${{ secrets.OTTO_TOKEN }} | gh auth login --with-token
          gh pr create \
            --title "Update ${{ env.SUBMODULE_PATH }} to version ${{ env.RELEASE_VERSION }}" \
            --body "This PR updates the submodule ${{ env.SUBMODULE_PATH }} to version ${{ env.RELEASE_VERSION }}." \
            --base main \
            --head ${{ env.BRANCH_NAME }}
