name: Handle Submodule Trigger

on:
  repository_dispatch:
    types:
      - trigger-dependabot-update

jobs:
  update-dependencies:
    strategy:
      matrix:
        branch-name:
          - main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "${{ matrix.branch-name }}"

      # Run Dependabot update
      - name: Run Dependabot Update
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.DEPENDABOT_TOKEN }}"
